lib: Define enum ofperr before using it.
Header file lib/tun-metadata.h declares functions using enum ofperr
without including a definition for this enum. While this is Ok for C
where enums can be implicitly converted to/from int, C++ compilers throw
an error about this, for example (for clang++):

error: ISO C++ forbids forward references to 'enum' types

For GCC, this can be reproduced with command `g++ lib/tun-metadata.h
-Iinclude` from the root of Open vSwitch repository. This patch includes
the necessary header file and also conditionally adds extern "C"
directive.